config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :services
  resources :contacts
  resources :professional_users
  resources :normal_users
  resources :schedules
  resources :conversations do
  resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  #get 'sessions/new'
  get 'mensagens', to: 'conversations#index'
  get 'cadastro', to: 'static_pages#cadastro'
  get 'cadastro_cliente', to: 'normal_users#new'
  get 'cadastro_profissional', to: 'professional_users#new'
  get 'login_cliente', to: 'login_cliente#new'
  post 'login_cliente', to: 'login_cliente#create'
  get 'login_profissional', to: 'login_profissional#new'
  post 'login_profissional', to: 'login_profissional#create'
  get 'entrar', to: 'login_users#new'
  get 'meus_servicos', to: 'services#index'
  get 'meus_enderecos', to: 'addresses#index'
  # post 'entrar', to:  'login_users#new'
  get 'temp', to: 'static_pages#temp'
  delete 'saircliente', to: 'login_cliente#destroy'
  delete 'sairprofissional', to: 'login_profissional#destroy'
  get 'servicos_profissional', to:'services#professional_services'
  get 'busca_profissional', to:'professional_users#index'
  get 'busca_servico_nome', to: 'services#services_name'
  get 'busca_endereco_nome', to: 'services#addresses_names'
  get 'busca_profissional_profissao', to: 'professional_users#professionals_profession'
  get '/:id' => 'professional_users#profile_professional_user', as: :perfil_profissional
  #get 'servicos_profissional', to: 'professional_users#professional_services'
  #get 'editar_profissional', to: 'professional_users#edit'
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :address

    validates :service, presence: true, length: { maximum: 50 }
    validates :description, presence: true, length: { maximum: 500 }
    validates :value, presence: true, length: { maximum: 4 }
    validates :duration, presence: true, length: { maximum: 1 }
    validates :address_id, presence: true

    belongs_to :professional_user
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in_professional_user, only: [:index, :show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = current_professional_user.services
  end

  def professional_services
    #@services = Service.all
    @services = Service.where(professional_user_id: params[:id])
  end

  def services_name
    if params[:search].nil? || params[:search] == ""
      @services = nil
    else
      @services = Service.where("service ILIKE ?", "%#{params[:search]}%")
      @professional = Service.joins(:professional_user).where(professional_users: params[:id])
      if params[:search].present?
        if @services.empty?
          flash.now[:danger] = 'Serviço não encontrado!'
        end
      end
    end
  end

  def addresses_names
    if params[:search].nil? || params[:search] == ""
      @services = nil
    else
      @services = Service.joins(:address).where("city ILIKE ?", "%#{params[:search]}%")
      @professional = Service.joins(:professional_user).where(professional_users: params[:id])
      if params[:search].present?
        if @services.empty?
          flash.now[:danger] = 'Não serviços cadastrados com esta cidade!'
        end
      end
    end
  end


  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = current_professional_user.services.build(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to meus_servicos_path }
        flash[:success] = 'Serviço adicionado com sucesso!'
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    @service = current_professional_user.services.find(params[:id])
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to meus_servicos_path }
        flash[:success] = 'Serviço atualizado com sucesso!'
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = current_professional_user.services.find(params[:id])
    @service.destroy
    redirect_to services_url
    flash[:success] = 'Serviço excluído com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit( :service, :description, :value, :duration, :email, :address_id )
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
  <% if service.errors.any? %>
    <div>
    <div class="alert alert-danger">
      <ul>
      <h3>Ops! Encontramos <%= pluralize(service.errors.count, 'erro', 'erros') %> </h3>


      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :service, "Nome" %>
    <%= form.text_field :service, class: 'form-control', id: 'nome_serviço' %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Descrição" %>
    <%= form.text_area :description, class: 'form-control', id:'descrição_serviço' %>
  </div>

  <div class="form-group">
    <%= form.label :value, "Preço" %>
    <%= form.number_field :value, class: 'form-control', id: 'preço_serviço' %>
  </div>

  <div class="form-group">
    <%= form.label :duration, "Duração (em horas)" %>
    <%= form.number_field :duration, max: 9, class: 'form-control', id: 'duração_serviço' %>
  </div>

  <div class="form-group">
    <%= form.label :address_id, "Endereço (horários de atendimento já inclusos no endereço)" %>
    <%= form.collection_select :address_id, current_professional_user.addresses.order(:name), :id, :name, {}, {id: "selecionar-endereco", class: "form-control" } %>
  </div>

app/views/services/addresses_names.html.erb
<br>
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
	<h3 class="center">Buscar por cidade</h3>
    <div class="well well-large">
        <div class="form-group center">
            <%= form_tag(busca_endereco_nome_path, :method => :get) do %>
				<div class="col-sm-7">
                	<%= text_field_tag 'search', nil, class: 'form-control', placeholder: 'Digite o nome da cidade que deseja encontrar' %>
				</div>
				<%= submit_tag 'Buscar', class:' btn btn-verde' %>
            <% end %>
        </div>
    </div>

	<% if !@services.nil? %>
		<% @services.each do |service| %> <!-- Serviços -->
			<br>
			<div class="well well-large"> <!-- Card -->
				<h4 class="center"><strong><%= service.service.upcase %></strong></h4>
				<strong>Profissional:</strong> <%= service.professional_user.name + " | " + service.professional_user.profession.titlecase %>
				<%= fa_icon "angle-double-right" %>
				<strong><%= link_to 'Visitar Perfil', perfil_profissional_path(service.professional_user.id), class: "verde" %></strong><br><br>
				<strong>Descrição:</strong> <%= service.description %><br><br>
				<strong>Valor:</strong> R$ <%= service.value %>,00 |
				<strong>Duração:</strong> <%= service.duration %>h<br>
				<br><strong>Endereço:</strong><br>
				<%= service.address.name + ", " + service.address.number + " | " %>
				<strong>Complemento: </strong>
				<%= service.address.description  %><br>
				<strong>CEP: </strong>
				<%=  service.address.postal_code + " - " + service.address.district + ", " + service.address.city + ", " + service.address.state.upcase %><br>
				<% if !service.address.schedules.empty? %> <!-- Se não for vazio -->
					<br>
					<strong>Horários de atendimento:</strong><br>
					<% service.address.schedules.each do |schedule| %> <!-- Cada um dos horários -->
					<% if schedule.day != "sábado" and schedule.day != "domingo" %> <!-- Para colocar feira no dia -->
						<%= schedule.day.capitalize + "-feira" %>
					<% else %>
						<%= schedule.day.capitalize %>
					<% end %> <!-- Para colocar feira no dia -->
					<% if schedule.morning == "true" %> <!-- Se for de manhã -->
						| Manhã
					<% end %> <!-- Se for de manhã -->
					<% if schedule.evening == "true" %> <!-- Se for de tarde -->
						| Tarde
					<% end %> <!-- Se for de tarde -->
					<% if schedule.night == "true" %> <!-- Se for de noite -->
						| Noite
					<% end %> <!-- Se for de noite -->
					<br>
					<% end %> <!-- Cada um dos horários -->
				<% end %> <!-- Se não for vazio -->
			</div> <!--Card -->

		<% end %> <!-- Serviços -->
	<% end %>

	<div class="center">
		<%= link_to 'Voltar', login_cliente_path, class: "btn btn-cinza" %>
	</div>

</div> <!--Container -->

app/views/services/edit.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
  <h1>Editar serviço</h1>
  <%= form_with(model: @service, local: true) do |form| %>
    <%= render 'form', service: @service, form: form %>

    <div class="actions">
      <div class="center">
        <%= form.submit 'Salvar', class: 'btn btn-verde' %>
      </div>

      <div class="center">
        <%= link_to 'Voltar', services_path, class: 'btn btn-cinza' %>
      </div>
    </div>
  <% end %>
</div>

app/views/services/index.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12 container"> <!-- Container -->
  <h1>Meus Serviços</h1>

  <% if @services.empty? %>
    <div class="well well-large">
      <tr>
        <td colspan="4" class="text-center">
          <h3>Sem serviços cadastrados.</h3>
          <%= link_to 'Clique aqui', new_service_path %> para cadastrar um novo serviço
        </td>
      </tr>
    </div>
  <% end %>


  <% @services.each do |service| %> <!-- Serviços -->
    <br>
    <div class="well well-large"> <!-- Card -->
      <h4 class="center"><strong><%= service.service.upcase %></strong></h4>
      <strong>Descrição:</strong> <%= service.description %><br><br>
      <strong>Valor:</strong> R$ <%= service.value %>,00 |
      <strong>Duração:</strong> <%= service.duration %>h<br>
      <br><strong>Endereço:</strong><br>
      <%= service.address.name + ", " + service.address.number + " | " %>
      <strong>Complemento: </strong>
      <%= service.address.description  %><br>
      <strong>CEP: </strong>
      <%=  service.address.postal_code + " - " + service.address.district + ", " + service.address.city + ", " + service.address.state.upcase %><br>
      <% if !service.address.schedules.empty? %> <!-- Se não for vazio -->
        <br>
        <strong>Horários de atendimento:</strong><br>
        <% service.address.schedules.each do |schedule| %> <!-- Cada um dos horários -->
          <% if schedule.day != "sábado" and schedule.day != "domingo" %> <!-- Para colocar feira no dia -->
            <%= schedule.day.capitalize + "-feira" %>
          <% else %>
            <%= schedule.day.capitalize %>
          <% end %> <!-- Para colocar feira no dia -->
          <% if schedule.morning == "true" %> <!-- Se for de manhã -->
            | Manhã
          <% end %> <!-- Se for de manhã -->
          <% if schedule.evening == "true" %> <!-- Se for de tarde -->
            | Tarde
          <% end %> <!-- Se for de tarde -->
          <% if schedule.night == "true" %> <!-- Se for de noite -->
            | Noite
          <% end %> <!-- Se for de noite -->
          <br>
        <% end %> <!-- Cada um dos horários -->
      <% end %> <!-- Se não for vazio -->

      <div class="center"> <!--Center -->
        <br>
        <%= link_to 'Editar', edit_service_path(service), class: 'btn btn-cinza'%>
        <%= link_to 'Apagar', service, method: :delete, data: { confirm: 'Confirma?' }, class: 'btn btn-cinza'%>
      </div> <!--Center -->
    </div> <!--Card -->

  <% end %> <!-- Serviços -->

  <div class="center">
    <%= link_to 'Adicionar serviço', new_service_path, class: 'btn btn-verde', id: 'adicionar_serviços' %>
    <br><br>
    <%= link_to 'Voltar', login_profissional_path, class: "btn btn-cinza", id: 'Voltar' %>
  </div>

</div> <!--Container -->

app/views/services/new.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
    <h1>Novo serviço</h1>
    <%= form_with(model: @service, local: true) do |form| %>
        <%= render 'form', service: @service, form: form %>

        <br>
        <div class="actions">
            <div class="center">
                <%= form.submit 'Adicionar', class: 'btn btn-verde' %>
            </div>

            <div class="center">
                <%= link_to 'Voltar', services_path, class: 'btn btn-cinza' %>
            </div>
        </div>
    <% end %>
</div>

app/views/services/professional_services.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12 container"> <!-- Container -->
  <h1>Serviços</h1>

  <% if @services.empty? %>
    <div class="well well-large">
      <tr>
        <td colspan="4" class="text-center">
          <h3>Sem serviços cadastrados.</h3>
        </td>
      </tr>
    </div>
  <% end %>


  <% @services.each do |service| %> <!-- Serviços -->
    <br>
    <div class="well well-large"> <!-- Card -->
      <h4 class="center"><strong><%= service.service.upcase %></strong></h4>
      <strong>Descrição:</strong> <%= service.description %><br><br>
      <strong>Valor:</strong> R$ <%= service.value %>,00 |
      <strong>Duração:</strong> <%= service.duration %>h<br>
      <br><strong>Endereço:</strong><br>
      <%= service.address.name + ", " + service.address.number + " | " %>
      <strong>Complemento: </strong>
      <%= service.address.description  %><br>
      <strong>CEP: </strong>
      <%=  service.address.postal_code + " - " + service.address.district.capitalize + ", " + service.address.city.capitalize + ", " + service.address.state.upcase %><br>
      <% if !service.address.schedules.empty? %> <!-- Se não for vazio -->
        <br>
        <strong>Horários de atendimento:</strong><br>
        <% service.address.schedules.each do |schedule| %> <!-- Cada um dos horários -->
          <% if schedule.day != "sábado" and schedule.day != "domingo" %> <!-- Para colocar feira no dia -->
            <%= schedule.day.capitalize + "-feira" %>
          <% else %>
            <%= schedule.day.capitalize %>
          <% end %> <!-- Para colocar feira no dia -->
          <% if schedule.morning == "true" %> <!-- Se for de manhã -->
            | Manhã
          <% end %> <!-- Se for de manhã -->
          <% if schedule.evening == "true" %> <!-- Se for de tarde -->
            | Tarde
          <% end %> <!-- Se for de tarde -->
          <% if schedule.night == "true" %> <!-- Se for de noite -->
            | Noite
          <% end %> <!-- Se for de noite -->
          <br>
        <% end %> <!-- Cada um dos horários -->
      <% end %> <!-- Se não for vazio -->
    </div> <!--Card -->

  <% end %> <!-- Serviços -->

  <div class="center">
    <br>
    <%= link_to 'Voltar', :back, class: "btn btn-cinza" %>
  </div>

</div> <!--Container -->

app/views/services/services_name.html.erb
<br>
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
	<h3 class="center">Buscar um serviço pelo seu nome</h3>
    <div class="well well-large">
        <div class="form-group center">
            <%= form_tag(busca_servico_nome_path, :method => :get) do %>
				<div class="col-sm-7">
                	<%= text_field_tag 'search', nil, class: 'form-control', placeholder: 'Digite o nome do serviço que deseja encontrar' %>
				</div>
				<%= submit_tag 'Buscar', class:' btn btn-verde' %>
            <% end %>
        </div>
    </div>

	<% if !@services.nil? %>
		<% @services.each do |service| %> <!-- Serviços -->
			<br>
			<div class="well well-large"> <!-- Card -->
				<h4 class="center"><strong><%= service.service.upcase %></strong></h4>
				<strong>Profissional:</strong> <%= service.professional_user.name + " | " + service.professional_user.profession.titlecase %>
				<%= fa_icon "angle-double-right" %>
				<strong><%= link_to 'Visitar Perfil', perfil_profissional_path(service.professional_user.id), class: "verde", id: "Visitar" %></strong><br><br>
				<strong>Descrição:</strong> <%= service.description %><br><br>
				<strong>Valor:</strong> R$ <%= service.value %>,00 |
				<strong>Duração:</strong> <%= service.duration %>h<br>
				<br><strong>Endereço:</strong><br>
				<%= service.address.name + ", " + service.address.number + " | " %>
				<strong>Complemento: </strong>
				<%= service.address.description  %><br>
				<strong>CEP: </strong>
				<%=  service.address.postal_code + " - " + service.address.district + ", " + service.address.city + ", " + service.address.state.upcase %><br>
				<% if !service.address.schedules.empty? %> <!-- Se não for vazio -->
					<br>
					<strong>Horários de atendimento:</strong><br>
					<% service.address.schedules.each do |schedule| %> <!-- Cada um dos horários -->
					<% if schedule.day != "sábado" and schedule.day != "domingo" %> <!-- Para colocar feira no dia -->
						<%= schedule.day.capitalize + "-feira" %>
					<% else %>
						<%= schedule.day.capitalize %>
					<% end %> <!-- Para colocar feira no dia -->
					<% if schedule.morning == "true" %> <!-- Se for de manhã -->
						| Manhã
					<% end %> <!-- Se for de manhã -->
					<% if schedule.evening == "true" %> <!-- Se for de tarde -->
						| Tarde
					<% end %> <!-- Se for de tarde -->
					<% if schedule.night == "true" %> <!-- Se for de noite -->
						| Noite
					<% end %> <!-- Se for de noite -->
					<br>
					<% end %> <!-- Cada um dos horários -->
				<% end %> <!-- Se não for vazio -->
			</div> <!--Card -->

		<% end %> <!-- Serviços -->
	<% end %>

	<div class="center">
		<%= link_to 'Voltar', login_cliente_path, class: "btn btn-cinza" %>
	</div>

</div> <!--Container -->

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @service.service %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @service.value %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @service.duration %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>