config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :services
  resources :contacts
  resources :professional_users
  resources :normal_users
  resources :schedules
  resources :conversations do
  resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  #get 'sessions/new'
  get 'mensagens', to: 'conversations#index'
  get 'cadastro', to: 'static_pages#cadastro'
  get 'cadastro_cliente', to: 'normal_users#new'
  get 'cadastro_profissional', to: 'professional_users#new'
  get 'login_cliente', to: 'login_cliente#new'
  post 'login_cliente', to: 'login_cliente#create'
  get 'login_profissional', to: 'login_profissional#new'
  post 'login_profissional', to: 'login_profissional#create'
  get 'entrar', to: 'login_users#new'
  get 'meus_servicos', to: 'services#index'
  get 'meus_enderecos', to: 'addresses#index'
  # post 'entrar', to:  'login_users#new'
  get 'temp', to: 'static_pages#temp'
  delete 'saircliente', to: 'login_cliente#destroy'
  delete 'sairprofissional', to: 'login_profissional#destroy'
  get 'servicos_profissional', to:'services#professional_services'
  get 'busca_profissional', to:'professional_users#index'
  get 'busca_servico_nome', to: 'services#services_name'
  get 'busca_endereco_nome', to: 'services#addresses_names'
  get 'busca_profissional_profissao', to: 'professional_users#professionals_profession'
  get '/:id' => 'professional_users#profile_professional_user', as: :perfil_profissional
  #get 'servicos_profissional', to: 'professional_users#professional_services'
  #get 'editar_profissional', to: 'professional_users#edit'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def new
        redirect_to professional_user_path(current_professional_user) if professional_user_signed_in?
        redirect_to normal_user_path(current_normal_user) if normal_user_signed_in?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/cadastro.html.erb
<%= render "layouts/header" %>

<div>
	<div id="logo-login" class="row">
		<%= image_tag "logo.png",
        :alt => "Descricao img",
        :width => "150px",
        :height => "150px" %>
	</div>

	<div class="row">
		<h3 class="nome-app">Iggle</h3>
	</div>

	<br><br><br><br><br><br>

	<h3 class="center">Cadastre-se como:</h3>

    <div class="center">
    	<%= link_to 'Cliente', cadastro_cliente_path, class: 'btn btn-verde', name: 'Cliente' %>
    <div>

    <div class="center">
    	<%= link_to 'Profissional', cadastro_profissional_path, class: 'btn btn-cinza', name:'Profissional' %>
    </div>

</div>

app/views/static_pages/index.html.erb
<%= render "layouts/header" %>

<div>
	<div id="logo-login" class="row">
		<%= image_tag "logo.png",
        :alt => "Descricao img",
        :width => "150px",
        :height => "150px" %>
	</div>

	<div class="row">
		<h3 class="nome-app">Iggle</h3>
	</div>

	<br><br><br><br><br><br>

	<h3 class="center">Bem Vindo!</h3>

    <div class="center">
    	<%= link_to 'Login', entrar_path, class: 'btn btn-verde', name: 'Login' %>
    <div>

    <div class="center">
    	<%= link_to 'Cadastro', cadastro_path, class: 'btn btn-cinza', name:'Cadastro' %>
    </div>

</div>

app/views/static_pages/temp.html.erb
<%= render "layouts/header" %>

<div>
	<div id="logo-login" class="row">
		<%= image_tag "logo.png",
        :alt => "Descricao img",
        :width => "150px",
        :height => "150px" %>
	</div>

	<div class="row">
		<h3 class="nome-app">Iggle</h3>
	</div>

	<br><br><br><br><br><br>

	<h3 class="center">ÁREA EM CONSTRUÇÃO</h3>


    <div class="center">
    	<%= link_to 'Voltar', :back, class: 'btn btn-cinza' %>
    </div>

</div>