config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :services
  resources :contacts
  resources :professional_users
  resources :normal_users
  resources :schedules
  resources :conversations do
  resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  #get 'sessions/new'
  get 'mensagens', to: 'conversations#index'
  get 'cadastro', to: 'static_pages#cadastro'
  get 'cadastro_cliente', to: 'normal_users#new'
  get 'cadastro_profissional', to: 'professional_users#new'
  get 'login_cliente', to: 'login_cliente#new'
  post 'login_cliente', to: 'login_cliente#create'
  get 'login_profissional', to: 'login_profissional#new'
  post 'login_profissional', to: 'login_profissional#create'
  get 'entrar', to: 'login_users#new'
  get 'meus_servicos', to: 'services#index'
  get 'meus_enderecos', to: 'addresses#index'
  # post 'entrar', to:  'login_users#new'
  get 'temp', to: 'static_pages#temp'
  delete 'saircliente', to: 'login_cliente#destroy'
  delete 'sairprofissional', to: 'login_profissional#destroy'
  get 'servicos_profissional', to:'services#professional_services'
  get 'busca_profissional', to:'professional_users#index'
  get 'busca_servico_nome', to: 'services#services_name'
  get 'busca_endereco_nome', to: 'services#addresses_names'
  get 'busca_profissional_profissao', to: 'professional_users#professionals_profession'
  get '/:id' => 'professional_users#profile_professional_user', as: :perfil_profissional
  #get 'servicos_profissional', to: 'professional_users#professional_services'
  #get 'editar_profissional', to: 'professional_users#edit'
end

app/models/normal_user.rb
class NormalUser < ApplicationRecord
    has_secure_password
    has_one_attached :avatar

    before_save :email_downcase

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 50 }
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }
    validates :phone, presence: true, length: { minimum: 10, maximum: 11 }

    private
      def email_downcase
        self.email.downcase!
      end
end

app/controllers/normal_users_controller.rb
class NormalUsersController < ApplicationController
  before_action :set_normal_user, only: [:show, :edit, :update, :destroy]

  # GET /normal_users
  # GET /normal_users.json
  def index
    @normal_users = NormalUser.all
  end

  # GET /normal_users/1
  # GET /normal_users/1.json
  def show
    require_logged_in_normal_user

    begin
      @normal_user = NormalUser.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      @normal_user = nil
    end

    if !@normal_user.nil?
      if !current_normal_user.nil?
        if current_normal_user.id != @normal_user.id
          redirect_to current_normal_user
        end
      end
    end
  end

  # GET /normal_users/new
  def new
    @normal_user = NormalUser.new
  end

  # GET /normal_users/1/edit
  def edit
    @normal_user = current_normal_user
  end

  def update
    @normal_user = current_normal_user
    if @normal_user.update(normal_user_params)
      flash.now[:success] = 'Informações alteradas com sucesso!'
      render :edit
    else
      render :edit
    end
  end

  # POST /normal_users
  # POST /normal_users.json
  def create
    @normal_user = NormalUser.new(normal_user_params)


      if @normal_user.save
        flash[:success] = 'Usuário cadastrado com sucesso.'
        redirect_to root_path
      else
        render :new

      end
    end
  end

  # PATCH/PUT /normal_users/1
  # PATCH/PUT /normal_users/1.json

  # DELETE /normal_users/1
  # DELETE /normal_users/1.json
  def destroy
    @normal_user.destroy
    respond_to do |format|
      format.html { redirect_to normal_users_url, notice: 'Usuário excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_normal_user
      begin
        @normal_user = NormalUser.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        @normal_user = nil
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def normal_user_params
      params.require(:normal_user).permit(:name, :email, :phone, :password, :password_confirmation , :avatar)
    end

app/helpers/normal_users_helper.rb
module NormalUsersHelper
end

app/views/normal_users/_form.html.erb
<% if normal_user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <h3>Ops! Encontramos <%= pluralize(normal_user.errors.count, 'erro', 'erros') %> </h3>


      <% normal_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control', id:"user_name" %>
</div>

<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, class: 'form-control', id:"user_email" %>
</div>

<div class="form-group">
  <%= form.label :phone %>
  <%= form.text_field :phone, class: 'form-control', id:"user_phone" %>
</div>

<div class="form-group">
  <%= form.label :password %>
  <%= form.password_field :password, class: 'form-control', id:'user_password' %>
</div>

<div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class: 'form-control', id:'user_passwordc' %>
</div>

<div class="form-group">
  <%= form.label :avatar %>
  <%= form.file_field :avatar, class: 'form-control' %>
</div>

app/views/normal_users/edit.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
  <h1>Alterar conta</h1>
  <%= form_with(model: @normal_user, local: true) do |form| %>
    <%= render 'form', normal_user: @current_normal_user, form: form %>


    <div class="actions">
      <div class="center">
        <%= form.submit 'Salvar', class: 'btn btn-verde', name: 'Salvar' %>
      </div>

      <div class="center">
        <%= link_to 'Voltar', @normal_user, class: 'btn btn-cinza' %>
      </div>
    </div>
  <% end %>
</div>

app/views/normal_users/index.html.erb
<%= render "layouts/header" %>

<h1 class="center">...</h1>

app/views/normal_users/new.html.erb
<%= render "layouts/header" %>

<div class="col-md-6 col-md-offset-3 col-xs-12 container">
  <h1>Cadastro</h1>
  <%= form_with(model: @normal_user, local: true) do |form| %>
    <%= render 'form', normal_user: @normal_user, form: form %>


    <div class="actions">
      <div class="center">
        <%= form.submit 'Cadastrar', class: 'btn btn-verde', name: 'Salvar' %>
      </div>

      <div class="center">
        <%= link_to 'Voltar', :back, class: 'btn btn-cinza' %>
      </div>
    </div>
  <% end %>
</div>

app/views/normal_users/show.html.erb
<div class="bg-cliente">
  <button id="openbtn" class="openbtn" onclick="openNav()">&#9776;</button>

  <h5 class="nome-user">
    <%= @normal_user.name %>
  </h5>

  <!-- SIDEBAR -->
  <nav id="mySidebar" class="sidebar">
    <div class="sidebar-header">
      <a href="javascript:void(0)" class="closebtn sidebar-header" onclick="closeNav()">&times;</a>
      <%= @normal_user.name %>
      <hr>
    </div>
    <div class="sidebar-links">
      <%= link_to "Conta", edit_normal_user_path, id: 'Conta' %>
      <%= link_to "Suporte", "#signup", 'data-target' => "#modal-mensagem", 'data-toggle' => "modal", name: 'Suporte'%>
      <%= link_to 'Sair', saircliente_path, method: :delete, id: 'Show'%>
    </div>
  </nav>
  <!-- FINAL DA SIDEBAR -->
    <div class="div-profile center" id="picture">
      <% if @normal_user.avatar.attached? %>
        <%= image_tag @normal_user.avatar,
          :alt => "profile picture",
          class: "img-profile" %>
      <% else %>
          <%= image_tag 'no_avatar.jpg',
          :alt => "No profile picture",
          class: "img-profile" %>
      <% end %>
    </div>
</div>

<div id="conteudo" class="main">
  <div class="container">
    <div class="right">
      <%= link_to fa_icon('envelope'), mensagens_path, id: "mensagem" %>
      <%= link_to fa_icon('star'), temp_path, id:"avaliacao" %>
    </div>

    <br><br><br><br><br>

    <div class="center">
      <h4 class="buscar">BUSCAR SERVIÇOS POR:</h4><br>

      <%= link_to "Profissional", busca_profissional_path, class: "btn btn-filtro", id: "busca-profissional" %>
      <%= link_to "Serviço", busca_servico_nome_path, class: "btn btn-filtro", id: "busca-servico-nome" %>
      <%= link_to "Localidade", busca_endereco_nome_path, class: "btn btn-filtro", id: "busca-servico-cidade" %>
      <%= link_to "Especialidade", busca_profissional_profissao_path, class: "btn btn-filtro", id: "busca-profissional-profissao" %>
    </div>

    <br>

    <div class="row container">
      <%= link_to temp_path, class: "col-sm-6", id: "atendimento_marcado" do %>
        <div class="card-atendimento">
          <h5>ATENDIMENTOS MARCADOS</h5>
        </div>
      <% end %>

      <%= link_to temp_path, class: "col-sm-6", id: "historico_atendimento" do %>
        <div class="card-atendimento">
          <h5>HISTÓRICO DE ATENDIMENTOS</h5>
        </div>
      <% end %>
    <!-- Final do modal -->
    </div><!-- Row -->
  </div> <!-- Container -->
</div>