config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :services
  resources :contacts
  resources :professional_users
  resources :normal_users
  resources :schedules
  resources :conversations do
  resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  #get 'sessions/new'
  get 'mensagens', to: 'conversations#index'
  get 'cadastro', to: 'static_pages#cadastro'
  get 'cadastro_cliente', to: 'normal_users#new'
  get 'cadastro_profissional', to: 'professional_users#new'
  get 'login_cliente', to: 'login_cliente#new'
  post 'login_cliente', to: 'login_cliente#create'
  get 'login_profissional', to: 'login_profissional#new'
  post 'login_profissional', to: 'login_profissional#create'
  get 'entrar', to: 'login_users#new'
  get 'meus_servicos', to: 'services#index'
  get 'meus_enderecos', to: 'addresses#index'
  # post 'entrar', to:  'login_users#new'
  get 'temp', to: 'static_pages#temp'
  delete 'saircliente', to: 'login_cliente#destroy'
  delete 'sairprofissional', to: 'login_profissional#destroy'
  get 'servicos_profissional', to:'services#professional_services'
  get 'busca_profissional', to:'professional_users#index'
  get 'busca_servico_nome', to: 'services#services_name'
  get 'busca_endereco_nome', to: 'services#addresses_names'
  get 'busca_profissional_profissao', to: 'professional_users#professionals_profession'
  get '/:id' => 'professional_users#profile_professional_user', as: :perfil_profissional
  #get 'servicos_profissional', to: 'professional_users#professional_services'
  #get 'editar_profissional', to: 'professional_users#edit'
end

app/models/professional_user.rb
class ProfessionalUser < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  before_save :email_downcase

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }
  validates :phone, presence: true, length: { minimum: 10, maximum: 11 }
  validates :document, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 500 }

  has_many :services
  has_many :addresses
  private
  def email_downcase
    self.email.downcase!
  end
end

app/controllers/professional_users_controller.rb
class ProfessionalUsersController < ApplicationController
  before_action :set_professional_user, only: [:show, :edit, :update, :destroy]

  # GET /professional_users
  # GET /professional_users.json
  def index
    if params[:search].nil? || params[:search] == ""
      @professional_users = nil
    else
      @professional_users = ProfessionalUser.where("name ILIKE ?", "%#{params[:search]}%")
      if params[:search].present?
        if @professional_users.empty?
          flash.now[:danger] = 'Profissional não encontrado!'
        end
      end
    end
  end

  def professionals_profession
    @professional_users = ProfessionalUser.where(profession: params[:search])
    if params[:search].present?
      if @professional_users.empty?
        flash.now[:danger] = "Não existe nenhum profissional com esta especialidade cadastrado."
      end
    end
  end

  # GET /professional_users/1
  # GET /professional_users/1.json
  def show
    require_logged_in_professional_user

    begin
      @professional_user = ProfessionalUser.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      @professional_user = nil
    end

    if !@professional_user.nil?
      if !current_professional_user.nil?
        if current_professional_user.id != @professional_user.id
          redirect_to current_professional_user
        end
      end
    end
  end

  def profile_professional_user
    @professional_user = ProfessionalUser.find(params[:id])
  end

  def professional_services
    @professional_user = ProfessionalUser.find(params[:id])
    @services = @professsional_user.services
  end

  # GET /professional_users/new
  def new
    @professional_user = ProfessionalUser.new
  end

  # GET /professional_users/1/edit
  def edit
    @professional_user = current_professional_user
  end

  def update
    @professional_user = current_professional_user
    if @professional_user.update(professional_user_params)
      flash.now[:success] = 'Informações alteradas com sucesso!'
      render :edit
    else
      render :edit
    end
  end
  # POST /professional_users
  # POST /professional_users.json
  def create
    @professional_user = ProfessionalUser.new(professional_user_params)


      if @professional_user.save
        flash[:success] = 'Usuário cadastrado com sucesso.'
        redirect_to root_path
      else
        render :new

      end
    end
  end

  # PATCH/PUT /professional_users/1
  # PATCH/PUT /professional_users/1.json

  # DELETE /professional_users/1
  # DELETE /professional_users/1.json
  def destroy
    @professional_user.destroy
    respond_to do |format|
      format.html { redirect_to professional_users_url, notice: 'Conta excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional_user
      begin
        @professional_user = ProfessionalUser.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        @professional_user = nil
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professional_user_params
      params.require(:professional_user).permit(:name, :email, :phone, :profession, :document, :description, :facebook, :instagram, :password, :password_confirmation, :avatar)
    end

app/helpers/professional_users_helper.rb
module ProfessionalUsersHelper
end

app/views/professional_users/_form.html.erb
<% if professional_user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <h3>Ops! Encontramos <%= pluralize(professional_user.errors.count, 'erro', 'erros') %> </h3>


      <% professional_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control', id: 'profissional_name', placeholder: 'Nome completo' %>
</div>

<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, class: 'form-control', id: 'profissional_email', placeholder: 'Email'%>
</div>

<div class="form-group">
  <%= form.label :phone %>
  <%= form.text_field :phone, class: 'form-control', id: 'profissional_phone', placeholder: 'Número telefone'%>
</div>

<div class="form-group">
  <%= form.label :profession %>
  <%= form.select :profession, [["Nutricionista", "nutricionista"], ["Nutrólogo", "nutrólogo"], ["Professor de Esportes", "professor de esportes"], ["Prof. de Educação Física", "profissional de educação física"]], {}, {class: 'form-control'} %>
</div>

<div class="form-group">
  <%= form.label :document %>
  <%= form.text_field :document, class: 'form-control', id: 'profissional_document', placeholder: 'Número documento'  %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: 'form-control', id: 'profissional_description', placeholder: 'Descrição' %>
</div>

<div class="form-group">
  <%= form.label :facebook %>
  <%= form.text_field :facebook, class: 'form-control', id: 'profissional_facebook', placeholder:"URL: http://www.facebok.com/Maria.Silva" %>
</div>

<div class="form-group">
  <%= form.label :instagram %>
  <%= form.text_field :instagram, class: 'form-control', id: 'profissional_instagram', placeholder:'Nome do usuário' %>
</div>

<div class="form-group">
  <%= form.label :password %>
  <%= form.password_field :password, class: 'form-control', id: 'profissional_password', placeholder:"Senha"  %>
</div>

<div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class: 'form-control', id: 'profissional_passwordc', placeholder:"Senha" %>
</div>

<div class="form-group">
  <%= form.label :avatar %>
  <%= form.file_field :avatar, class: 'form-control' %>
</div>

app/views/professional_users/edit.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
  <h1>Alterar conta</h1>
  <%= form_with(model: @professional_user, local: true) do |form| %>
    <%= render 'form', professional_user: @current_professional_user, form: form %>

    <div class="actions">
      <div class="center">
        <%= form.submit 'Salvar', class: 'btn btn-verde', name: 'Salvar' %>
      </div>

      <div class="center">
        <%= link_to 'Voltar', @professional_user, class: 'btn btn-cinza' %>
      </div>
    </div>
  <% end %>
</div>

app/views/professional_users/index.html.erb
<br>
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
	<h3 class="center">Buscar um profissional pelo seu nome</h3>
    <div class="well well-large">
        <div class="form-group center">
            <%= form_tag(professional_users_path, :method => :get) do %>
                <div class="col-sm-7">
                    <%= text_field_tag 'search', nil, class: 'form-control form-style', placeholder:'Digite o nome do profissional que deseja encontrar' %>
                </div>
                <%= submit_tag 'Buscar', class:' btn btn-verde'%>
            <% end %>
            <br>
        </div>
    </div>

    <% if !@professional_users.nil? %>
        <% if !@professional_users.empty? %>
            <table class="table">
                <thead>
                    <tr>
                        <th class="center">Nome</th>
                        <th class="center">Profissão</th>
                        <th class="center">Perfil</th>
                        <th class="center">Serviços</th>
                    </tr>
                </thead>

                <tbody class="center">
                    <% @professional_users.each do |professional_user| %>
                        <tr>
                            <td><%= professional_user.name %></td>
                            <td><%= professional_user.profession.titlecase %></td>
                            <td><%= link_to 'Visitar', perfil_profissional_path(professional_user.id), id: 'Visitar' %></td>
                            <td><%= link_to "Visualizar", servicos_profissional_path(id: professional_user.id) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    <% end %>

    <div class="center">
        <br>
        <%= link_to 'Voltar', login_cliente_path, class: "btn btn-cinza" %>
    </div>
</div>

app/views/professional_users/new.html.erb
<%= render "layouts/header" %>

<div class="col-md-6 col-md-offset-3 col-xs-12 container">
  <h1>Cadastro</h1>
  <%= form_with(model: @professional_user, local: true) do |form| %>
    <%= render 'form', professional_user: @professional_user, form: form %>

    <div class="actions">
      <div class="center">
        <%= form.submit 'Cadastrar', class: 'btn btn-verde', name: 'Salvar' %>
      </div>

      <div class="center">
        <%= link_to 'Voltar', @professional_user, class: 'btn btn-cinza' %>
      </div>
    </div>
  <% end %>
</div>

app/views/professional_users/professionals_profession.html.erb
<br>
<div class="col-md-6 col-md-offset-3 col-xs-12 container">
	<h3 class="center">Busque um profissional por sua especialidade</h3>
    <div class="well well-large">
        <div class="form-group center">
            <%= form_tag(busca_profissional_profissao_path, :method => :get) do %>
                <div class="col-sm-7">
					  <%= select_tag 'search', options_for_select([["Nutricionista", "nutricionista"],
					  ["Nutrólogo", "nutrólogo"],
					  ["Professor de Esportes", "professor de esportes"],
					  ["Prof. de Educação Física", "profissional de educação física"]]), class: "form-control" %>
			    </div>
                <%= submit_tag 'Buscar', class:' btn btn-verde'%>
            <% end %>
            <br>
        </div>
    </div>

    <% if @professional_users.empty? %>

    <% else %>
        <table class="table">
            <thead>
                <tr>
                    <th class="center">Nome</th>
                    <th class="center">Perfil</th>
                    <th class="center">Serviços</th>
                </tr>
            </thead>

            <tbody class="center">
                <% @professional_users.each do |professional_user| %>
                    <tr>
                        <td><%= professional_user.name %></td>
                        <td><%= link_to 'Visitar', perfil_profissional_path(professional_user.id), id: 'Visitar'%></td>
                        <td><%= link_to "Visualizar", servicos_profissional_path(id: professional_user.id), id: 'Visualizar' %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>

    <div class="center">
        <br>
        <%= link_to 'Voltar', login_cliente_path, class: "btn btn-cinza" %>
    </div>
</div>

app/views/professional_users/profile_professional_user.html.erb
<div class="bg-profissional">
  <br>
  <span class="nome-user"><%= @professional_user.name %></span>
</div>

    <div class="div-profile center">
      <% if @professional_user.avatar.attached? %>
        <%= image_tag @professional_user.avatar,
          :alt => "profile picture",
          class: "img-profile" %>
      <% else %>
          <%= image_tag 'no_avatar.jpg',
          :alt => "No profile picture",
          class: "img-profile" %>
      <% end %>
    </div>

<div id="conteudo" class="main">
  <div class="container">
    <div class="left">
      <% if @professional_user.facebook != "" %>
        <%= link_to fa_icon('facebook'), @professional_user.facebook, id: "facebook", class:'verde', target: :_blank %>
      <% end %>

      <% if @professional_user.instagram != "" %>
        <%= link_to fa_icon('instagram'), "https://www.instagram.com/" + @professional_user.instagram, id: "instagram", class: 'verde', target: :_blank %>
      <% end %>
    </div>

    <div class="right">
      <%#= link_to fa_icon('bell'), temp_path, id: "notificacao" %>
      <%= link_to fa_icon('envelope'), temp_path, id: "chat" %>
      <%= link_to fa_icon('star'), temp_path, id: "avaliacao" %>
    </div>
    <br><br><br><br><br>
    <div class="description">
      <%= @professional_user.description %><br><br>
      <strong>Telefone:</strong> <%= "(" + @professional_user.phone[0..1] + ") " + @professional_user.phone[2..-1] %><br>
      <strong>E-mail:</strong> <%= @professional_user.email %><br><br>
      <strong>Formação:</strong> <%= @professional_user.profession.titlecase + " | " %>
      <% if @professional_user.profession == "nutricionista" %>
        <strong>CRN:</strong> <%= @professional_user.document %><br>
      <% elsif @professional_user.profession == "nutrólogo" %>
        <strong>CRM:</strong> <%= @professional_user.document %><br>
      <% else %>
        <strong>CONFEF:</strong> <%= @professional_user.document %><br>
      <% end %>
    </div>
    <hr>
    <div class="col-md-12">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <%= link_to servicos_profissional_path(id: @professional_user.id), id:'serviços' do %>
          <div class="card-atendimento">
            <h5>SERVIÇOS</h5>
          </div>
        <% end %>
      </div>
      <div class="col-md-4">
      </div>
    </div>

    <div class="center">
      <%= link_to 'Voltar', login_cliente_path, class: "btn btn-cinza" %>
    </div>

  </div> <!-- Container -->
</div>

app/views/professional_users/show.html.erb
<div class="bg-profissional">
  <button id="openbtn" class="openbtn" onclick="openNav()">&#9776;</button>

  <h5 class="nome-user">
    <%= @professional_user.name %>
  </h5>

  <!-- SIDEBAR -->
  <nav id="mySidebar" class="sidebar">
    <div class="sidebar-header">
      <a href="javascript:void(0)" class="closebtn sidebar-header" onclick="closeNav()">&times;</a>
      <%= @professional_user.name %>
      <hr>
    </div>
    <div class="sidebar-links">
      <%= link_to "Conta", edit_professional_user_path, id: 'Conta' %>
      <%= link_to "Endereços", meus_enderecos_path, id: 'Endereços' %>
      <%= link_to "Suporte", "#signup", 'data-target' => "#modal-mensagem", 'data-toggle' => "modal", name: 'Suporte'%>
      <%= link_to 'Sair', sairprofissional_path, method: :delete, id: 'Sair' %>
    </div>
  </nav>
</div>

    <div class="div-profile center" id="picture">
      <% if @professional_user.avatar.attached? %>
        <%= image_tag @professional_user.avatar,
          :alt => "profile picture",
          class: "img-profile" %>
      <% else %>
          <%= image_tag 'no_avatar.jpg',
          :alt => "No profile picture",
          class: "img-profile" %>
      <% end %>
    </div>
</div>

<div id="conteudo" class="main">
  <div class="container">
    <div class="left">
      <% if @professional_user.facebook != "" %>
        <%= link_to fa_icon('facebook'), @professional_user.facebook, id: "facebook", class:'verde', target: :_blank %>
      <% else %>
        <%= link_to fa_icon('facebook'), @professional_user.facebook, id: "facebook", :title => "Você não possui um facebook cadastrado" %>
      <% end %>

      <% if @professional_user.instagram != "" %>
        <%= link_to fa_icon('instagram'), "https://www.instagram.com/" + @professional_user.instagram, id: "instagram", class: 'verde', target: :_blank %>
      <% else %>
        <%= link_to fa_icon('instagram'), @professional_user.instagram, id: "instagram", :title => "Você não possui um instagram cadastrado" %>
      <% end %>
    </div>

    <div class="right">
      <%#= link_to fa_icon('bell'), temp_path, id: "notificacao" %>
      <%= link_to fa_icon('envelope'), temp_path, id: "chat" %>
      <%= link_to fa_icon('star'), temp_path, id: "avaliacao" %>
    </div>
    <br><br><br><br><br>
    <div class="description">
      <%=@professional_user.description %>
    </div>
    <hr>
    <div class="row container">
      <%= link_to meus_servicos_path, class: "col-md-4", id: "serviços" do %>
        <div class="card-atendimento">
          <h5>SERVIÇOS</h5>
        </div>
      <%end%>

      <%= link_to temp_path, class: "col-md-4" do %>
        <div class="card-atendimento" id="atendimento_marcado">
          <h5>ATENDIMENTOS MARCADOS</h5>
        </div>
      <%end%>

      <%= link_to temp_path, class: "col-md-4" do %>
        <div class="card-atendimento" id="historico_consulta">
          <h5>HISTÓRICO DE ATENDIMENTOS</h5>
        </div>
      <%end%>
    </div><!-- Row -->
    <br>
  </div> <!-- Container -->
</div>